<a href="https://colab.research.google.com/github/revendrat/AI-ML-Workshop-PIEMR-/blob/main/Mastering_Tensors_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
# Fetch the version of tensorflow
tf.__version__

'2.8.0'

In [ ]:
# Check if GPU is available
#tf.test.is_gpu_available () --> depricated
tf.config.list_physical_devices('GPU')

[]

In [ ]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

# Tensors
* Multidimensional arrays are also called tensors.
* Tensors are the basic data structure for machine-learning systems
* Tensor are containers of numerical data
* A dimension in tensors is also known an axis

## Key attributes of tensors
* A tensor has three key attributes
* First attribute: Rank or Number of axes
  * An array has 1-axis and also called as **1-rank tensor**
  * A matrix has 2-axes and also called as **2-rank tensor**
* Second Attribute: **Shape**
  * Describes the number of dimensions of a tensor
  * Example: 3-rank tensor with 20 records in each dimension has shape of (3,20, 20)
  * shape results are usually shown in tuple data structure
* Third Attribute: **Data Type**
  * Informs about the type of data contained in tensors
  * Example data types: float32, uint8, float64. etc.

## Examples of Tensors


In [ ]:
# Create a scalar in tensorflow
a = tf.constant(5.7)
a

<tf.Tensor: shape=(), dtype=float32, numpy=5.7>

In [ ]:
# Create an array
a= tf.constant([5.7, 70.5])
a

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5.7, 70.5], dtype=float32)>

Note that the above tensor array can return data into Numpy.array using numpy() method.
A quick illustration below

In [ ]:
a.numpy()

array([ 5.7, 70.5], dtype=float32)

In [ ]:
# To create vector, the structure of vector should be passed to tf.constant() function in the list container
a = tf.constant([5.7]) # creates vector with one element
print(a)
print(a.shape)

tf.Tensor([5.7], shape=(1,), dtype=float32)
(1,)


In [ ]:
# Create a vector with 3 elements
a = tf.constant([5.7, 70.5, 50.7])
print(a)
print(a.shape)

tf.Tensor([ 5.7 70.5 50.7], shape=(3,), dtype=float32)
(3,)


In [ ]:
# Create a matrix of size 2x2
a_mat = tf.constant([[1,2], [3,4]])
print(a_mat)
print(a_mat.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


In [ ]:
# Create a 3 dimensional tensor containing matrix of size 2x2
t_3d_mat = tf.constant([[[1,2], [3,4]], [[1,2], [3,4]]])
print(t_3d_mat)
print(t_3d_mat.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]], shape=(2, 2, 2), dtype=int32)
(2, 2, 2)


## Strings operations in tensorflow
* String data type is supposrted by tensorflow.
* tf.strings module provides methods to operate on strings
  * lower(), join(), lenght(), split() & other modules are available

In [ ]:

# create a string tensor
a_string = tf.constant('Welcome to Colab')
print(a_string)
print(a_string.shape)

tf.Tensor(b'Welcome to Colab', shape=(), dtype=string)
()


In [ ]:
# convert all characters in a string to lower case
tf.strings.lower(a_string)

<tf.Tensor: shape=(), dtype=string, numpy=b'welcome to colab'>

In [ ]:
# Fetch the length of the string
tf.strings.length(a_string)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [ ]:
# split the string by space (' ')
tf.strings.split(a_string, ' ')

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Welcome', b'to', b'Colab'], dtype=object)>

## Booleans in TensorFlow
* TensorFlow supports boolean operations 

In [ ]:
# create a boolean scalar in TF
a_bool = tf.constant(True)
print(a_bool)
print(a_bool.shape)

tf.Tensor(True, shape=(), dtype=bool)
()


In [ ]:
# create a boolean vector in TF
a_bool = tf.constant([True, False, True])
print(a_bool)
print(a_bool.shape)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)
(3,)


## Variable tensors in TF
* tf.Variable() method is used to create variable tensors
* The variable tensors are used to continuously update the values of tensors during operations such as multiplcation, optimisation etc.
* One may check if a variable is TF constant or TF variable using trainable attribute

In [ ]:
a = tf.constant([1,2,3,4])
print(a)
print(a.shape)
#print(a.trainable) # does not work when a variable is defined as constant in TF

a = tf.Variable([1,2,3,4])
print(a)
print(a.shape)
print(a.trainable)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
(4,)
True


## Create tensors from Arrays & Lists
* Python lists
* Numpy arrays
* all-0 or all-1 tensors
* customised numeric tensors
* tensors from known probablisitc distributions
* create sequences in tensors

In [ ]:
# Convert python list to a tensor using convert_to_tensor
py_list = [1,2,3,4,5]
print("type of pylist ", type(py_list))
a_tensor = tf.convert_to_tensor(py_list)
print(a_tensor)

type of pylist  <class 'list'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
# Convert Numpy array to a tensor using convert_to_tensor
import numpy as np
numpy_array = np.array([[1,2],[3,5]])
print("numpy_array type ", type(numpy_array))
print("numpy_array values ", numpy_array)
a_tensor = tf.convert_to_tensor(numpy_array)
print(a_tensor)

numpy_array type  <class 'numpy.ndarray'>
numpy_array values  [[1 2]
 [3 5]]
tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int64)


In [ ]:
## Create all-0 or all-1 tensors
all_z = tf.zeros([10])
print(all_z)
all_one = tf.ones([10])
print(all_one)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [ ]:
# Create matrices of all ones or zeros
a_zero = tf.zeros([3,2]) # creates 3x2 matrix of all 0s
print(a_zero)

a_one = tf.ones([2,3]) # creates 2x3 matrix of all 1s
print(a_one)



tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
## Combine tensors using concat 
all_zo = tf.concat([all_z,all_one], 0)
print(all_zo)

## Combine tensors using  stack
all_zo_s = tf.stack([all_z,all_one])
print(all_zo_s)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(20,), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(2, 10), dtype=float32)


## Create customised numeric tensors
* say a tensor with specific value of 3
* create using tf.fill([shape], value)


In [ ]:
#create a matrix of size 2x4 filled with 3s
a_3s = tf.fill([2,4], 3) 
a_3s

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 3, 3, 3],
       [3, 3, 3, 3]], dtype=int32)>

## Create tensors from known distributions
* Gaussian or normal using tf.random.normal([shape], mean =0, stddev=1)
* uniform using  tf.random.uniform([shape])

In [ ]:
# Create a 3x3 matrix with random values from normal distribution with mean 2 and sd =0.5
tensor_gaussian = tf.random.normal([3,3], mean=1, stddev=0.5)
tensor_gaussian

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.98239213, 0.9637159 , 0.9140198 ],
       [0.19655001, 0.73667455, 2.4508111 ],
       [0.55357563, 1.1810786 , 1.4821931 ]], dtype=float32)>

In [ ]:
# Create a 3x3 matrix with random values from normalUNIFORM distribution with MINIMUM VALUE =1 AND maximum value =10 
tensor_unif = tf.random.uniform([3,3], minval=1, maxval=10)
tensor_unif

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6.293449 , 2.3244448, 2.321828 ],
       [3.829122 , 7.477582 , 9.076074 ],
       [1.9950191, 3.574749 , 4.849058 ]], dtype=float32)>

## Create a sequence of tensor using tf.range()

In [ ]:
# create tensor with sequence from 0 to 9 (total 10 values)
a_seq = tf.range(10)
a_seq

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# create tensor with sequence from 0 to 20 (total 10 values) with a step of 2
a_seq = tf.range(20, delta = 2)
a_seq

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int32)>