<a href="https://colab.research.google.com/github/revendrat/AI-ML-Workshop-PIEMR-/blob/main/Mastering_Tensors_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Operations on Tensors in Tensorflow
* Aim is to understand how to perform different operations using tensors to accomplish some tasks
* A simple example:
  * Assume that a model is built and target values are predicted (y_pred). Your goal is to understand the loss or error between predicted (y_pred) and actual values (y_actual)

In [ ]:
import tensorflow as tf
# Fetch the version of tensorflow
tf.__version__

'2.8.0'

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# randomly select y_actual
y_actual = tf.constant([2,3,5,6])

#perform one hot encoding on y_actual
y_actual = tf.one_hot(y_actual, depth =10)

print("y_actual ", y_actual)

# select y_pred values
y_pred = tf.random.uniform([4,10])
print("y_pred :", y_pred)





y_actual  tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]], shape=(4, 10), dtype=float32)
y_pred : tf.Tensor(
[[0.5879855  0.30204177 0.9629952  0.5175954  0.21526897 0.11432147
  0.5890825  0.20960677 0.35786068 0.16826761]
 [0.53244174 0.00486767 0.3082614  0.5460769  0.9861394  0.06889808
  0.4663254  0.7325764  0.10567534 0.82533324]
 [0.54629576 0.66395736 0.00201464 0.905774   0.6539726  0.72630274
  0.6489345  0.94798875 0.14442885 0.62715995]
 [0.32091188 0.4217415  0.36511326 0.03994358 0.8926122  0.62725914
  0.6849884  0.8200642  0.25528193 0.6161177 ]], shape=(4, 10), dtype=float32)


In [ ]:
from tensorflow import keras
# calculate mean square error (MSE)

error_mse = tf.keras.losses.mse(y_actual, y_pred)
print(error_mse)
# calculate mean of MSE
error_mse_mean = tf.reduce_mean(error_mse)

print(error_mse_mean)

tf.Tensor([0.13129722 0.30082768 0.37962875 0.28224716], shape=(4,), dtype=float32)
tf.Tensor(0.2735002, shape=(), dtype=float32)


## Little complex operations on tesnors
* Create a neural network
* A linear layer with input of two samples & four features x[2,4], and three output nodes will have weight matrix of size 4x3, and bias matrix of size 3x1
* A neural network without activation function is linear layer (more about activation funcstions later)


In [ ]:
x = tf.random.normal([2,4]) # A tensor with 2 samples and 4 features
print("x : ", x)
w = tf.ones([4,3])
print("w : ", w)
b = tf.zeros([3])
print("b : ", b)

y_out = x@w+b
print("y_out : ", y_out)


x :  tf.Tensor(
[[ 0.90326923 -0.85022116 -2.3111942  -0.0884396 ]
 [ 0.00569569  1.111236    0.24795751  0.4568581 ]], shape=(2, 4), dtype=float32)
w :  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
b :  tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
y_out :  tf.Tensor(
[[-2.3465858 -2.3465858 -2.3465858]
 [ 1.8217472  1.8217472  1.8217472]], shape=(2, 3), dtype=float32)


## Indexing & slicing of tensors
* perform indexing and slicing of tensors

In [ ]:
# Create a 4D tensor
x = tf.random.normal([4,2,2,3])
x.shape

TensorShape([4, 2, 2, 3])

In [ ]:
# extract the first element in x
x[0]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 1.0272828 , -0.5173647 ,  1.6769823 ],
        [-0.134903  ,  0.40716332, -0.88842624]],

       [[ 1.3519623 ,  0.40762976, -2.4297454 ],
        [-0.40355507, -1.5361911 , -0.5308645 ]]], dtype=float32)>

In [ ]:
# extract the last element in x
x[3]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-1.4752935 ,  1.5069964 , -0.9460742 ],
        [ 0.02280555,  0.41231284, -0.475807  ]],

       [[-0.11120775, -1.4357595 ,  1.0543944 ],
        [-1.3432103 ,  0.6789179 , -0.5807117 ]]], dtype=float32)>

In [ ]:
# extract the last element in x
x[-1]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-1.4752935 ,  1.5069964 , -0.9460742 ],
        [ 0.02280555,  0.41231284, -0.475807  ]],

       [[-0.11120775, -1.4357595 ,  1.0543944 ],
        [-1.3432103 ,  0.6789179 , -0.5807117 ]]], dtype=float32)>

In [ ]:
# Fetch the second row of the first 4d tensor:
x[0][1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.3519623 ,  0.40762976, -2.4297454 ],
       [-0.40355507, -1.5361911 , -0.5308645 ]], dtype=float32)>

In [ ]:
# Fetch the second row and second column of the first 4-d tensor:
x[0][1][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.40355507, -1.5361911 , -0.5308645 ], dtype=float32)>

In [ ]:
# Fetch the second column and second column of the first 4-d tensor:
x[0][1][:1]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 1.3519623 ,  0.40762976, -2.4297454 ]], dtype=float32)>

In [ ]:
# Fetch the second column and second column of the first 4-d tensor:
x[0][1][:,2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-2.4297454, -0.5308645], dtype=float32)>