<a href="https://colab.research.google.com/github/revendrat/AI-ML-Workshop-PIEMR-/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Array**

* NumPy is used to work with arrays. 
* The array object in ***NumPy*** is called ***ndarray***.

***ndarray*** object can be created by using the ***array()*** function.

In [1]:
# import numpy library
import numpy as np

In [2]:
# Use arange() to create random 15 value array (1-d).
print(np.arange(15))

# use reshape(m,n) to create mxn matrix
print(np.arange(15).reshape(3,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# Create a numpy array
a = np.arange(15).reshape(3, 5)

In [4]:
# Check attributes
# a.ndim 
# a.shape
# a.size
# a.dtype
# a.itemsize
# a.data

print("a.ndim: ", a.ndim)
print("a.shape: ", a.shape)
print("a.size: ", a.size)
print("a.dtype: ", a.dtype)
print("a.itemsize: ", a.itemsize)
print("a.data: ", a.data)

a.ndim:  2
a.shape:  (3, 5)
a.size:  15
a.dtype:  int64
a.itemsize:  8
a.data:  <memory at 0x7f9f5d2679f0>


In [5]:
# Create a ndarray similar to "a" using array() function
b = np.array([np.arange(0,5), 5+ np.arange(0,5), 10+ np.arange(0,5) ])
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print("b.ndim: ", b.ndim)
print("b.shape: ", b.shape)
print("b.size: ", b.size)
print("b.dtype: ", b.dtype)
print("b.itemsize: ", b.itemsize)
print("b.data: ", b.data)

b.ndim:  2
b.shape:  (3, 5)
b.size:  15
b.dtype:  int64
b.itemsize:  8
b.data:  <memory at 0x7f9f5d267d70>


In [7]:
# Create a complex numbers ndarray
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [8]:
print("c.ndim: ", c.ndim)
print("c.shape: ", c.shape)
print("c.size: ", c.size)
print("c.dtype: ", c.dtype)
print("c.itemsize: ", c.itemsize)
print("c.data: ", c.data)

c.ndim:  2
c.shape:  (2, 2)
c.size:  4
c.dtype:  complex128
c.itemsize:  16
c.data:  <memory at 0x7f9f5d218050>


In [9]:
# Create a matrix of zeros using zeros()
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Create an identity matrix using ones()
# make sure to use data type (dtype = int16)
np.ones((4,4), dtype = np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
# Create an empty matrix using empty()
# creates a matrix of infinitesimal small values
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Use linspace() to create values between two numbers
# create 10 values between 0 and 1
print(np.linspace(0,1,10))

# create 9 values between 0 and 10
print(np.linspace(0,10,9))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [13]:
# Create multi-dimensional arrays
print("1-d array")
print(np.arange(6)) # 1-d array
print("2-d array")
print(np.arange(12).reshape(4, 3) ) #2-d array
print("3-d array")
print(np.arange(24).reshape(2, 3, 4)) #3-d array
print("4-d array")
print(np.arange(24).reshape(2, 3, 2, 2)) #4-d array

1-d array
[0 1 2 3 4 5]
2-d array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3-d array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
4-d array
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


# **Basic Operations**

* Arithmetic operators on arrays apply elementwise.
* A new array is created and filled with the result.

In [14]:
import numpy as np

In [15]:
# create a 1-d ndarray named "a"
a = np.array([20, 30, 40, 50])

# create a 1-d ndarray named "b"
b = np.arange(4)

print("a :", a)
print("b :", b)

a : [20 30 40 50]
b : [0 1 2 3]


In [16]:
# addition operations
print("a+b : ", a+b)
print("a+b+b : ", a+b+b)

a+b :  [20 31 42 53]
a+b+b :  [20 32 44 56]


In [17]:
# subtraction operations
c = a - b
print("c: ", c)

print("b-a: ", b-a)

c:  [20 29 38 47]
b-a:  [-20 -29 -38 -47]


In [18]:
# power operations
b**2

array([0, 1, 4, 9])

In [19]:
# multiplication operations
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [20]:
# boolean operations
a < 35

array([ True,  True, False, False])

# **Unary operations**
* Numpy unary operations are performed as methods of Numpy Objects

In [21]:
x = np.array((1,2,3,4,5), dtype = int)
print("x : ", x)
print("sum of x : ", x.sum())
print("min of x : ", x.min() )
print("max of x : ", x.max() )
print("mean of x : ", x.mean() )
#print("median of x : ", x.median() )
#print("sd of x : ", x.sd() )

x :  [1 2 3 4 5]
sum of x :  15
min of x :  1
max of x :  5
mean of x :  3.0


# **Matrix Operations**
* The product operator * operates elementwise in NumPy arrays.
* The matrix product performed using the @ operator (in python >=3.5) or the dot function or method.

In [22]:
# Create two matrices A and B using Numpy array() function
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])

print("Matrix A: \n", A)
print("Matrix B: \n", B)

Matrix A: 
 [[1 1]
 [0 1]]
Matrix B: 
 [[2 0]
 [3 4]]


In [23]:
# Element-wise product
A * B   

array([[2, 0],
       [0, 4]])

In [24]:
# matrix product
A @ B  

array([[5, 4],
       [3, 4]])

In [25]:
# another way of achieveing matrix product
A.dot(B)

array([[5, 4],
       [3, 4]])

In [26]:
# operators such as *= and += act as modifying existing arrays instead of creating new arrays

print( "A : \n", A)

A *= 3

print( "A *= 3 : \n ", A)

A : 
 [[1 1]
 [0 1]]
A *= 3 : 
  [[3 3]
 [0 3]]


In [27]:
C = np.ones((2,2), dtype=int)
print("C : \n", C)
A += C
print("A : \n", A)

C : 
 [[1 1]
 [1 1]]
A : 
 [[4 4]
 [1 4]]


# **Universal functions**
* np.add
* np.exp
* np.log
* np.sqrt
* np.square
and many more

In [28]:
print("A : \n", A)
print("B : \n", B)

print("A+B : \n", np.add(A,B))

A : 
 [[4 4]
 [1 4]]
B : 
 [[2 0]
 [3 4]]
A+B : 
 [[6 4]
 [4 8]]


In [29]:
print("A : \n", A)
print("exponential of A : \n", np.exp(A))

print("Log of A : \n", np.log(A))

A : 
 [[4 4]
 [1 4]]
exponential of A : 
 [[54.59815003 54.59815003]
 [ 2.71828183 54.59815003]]
Log of A : 
 [[1.38629436 1.38629436]
 [0.         1.38629436]]


In [30]:
print("A : \n", A)
print("Square of A : \n", np.square(A))

print("Square root of A : \n", np.sqrt(A))

A : 
 [[4 4]
 [1 4]]
Square of A : 
 [[16 16]
 [ 1 16]]
Square root of A : 
 [[2. 2.]
 [1. 2.]]


# **Indexing, Slicing and Iterating**
* One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
* Multi-dimensional arrays

In [31]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [32]:
# extract the fourth element
a[3]

27

In [33]:
# extract all elements
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [34]:
# extract all elements from 5th to 8th positions
a[4:8]

array([ 64, 125, 216, 343])

In [35]:
# from 5th element to last element in array
a[4:]

array([ 64, 125, 216, 343, 512, 729])

In [36]:
# from the first element in an array upto 8th element (including 8th element)
a[:8]

array([  0,   1,   8,  27,  64, 125, 216, 343])

# **Multidimensional array**
* Indexing, Slicing and Iterating

In [37]:
# a 3D array (two stacked 2D arrays)
c = np.array([[[  0,  1,  2],  
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [38]:
# Check the dimenstions of c ndarray
c.shape

(2, 2, 3)

In [39]:
# extract all elements
c[::]

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [40]:
# extract all elements
c[0:,:]

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [41]:
# extract first elements (2x3 matrix) on first axis
c[0:1,:]

array([[[ 0,  1,  2],
        [10, 12, 13]]])

In [42]:
# extract second elements (2x3 matrix) on first axis
c[1:,:]

array([[[100, 101, 102],
        [110, 112, 113]]])

In [43]:
# In both the matrices, fetch 2nd row 3rd & 2nd elements
c[:,1,[2,1]]

array([[ 13,  12],
       [113, 112]])

In [44]:
# In the 2nd matrix, fetch 2nd row 3rd & 2nd elements
c[1:,1,[2,1]]

array([[113, 112]])

# **Create field names for numpy array, and index by field names**

In [45]:
# Create field names n numpy array 
x = np.array([(1,2)], dtype=[('value','f4'), ('amount','c8')])

In [46]:
# Access the elements by field names in numpy array
print(x['amount'])
print(x['value'])

[2.+0.j]
[1.]


# **Stacking numpy arrays**
* hstack for horizontal stacking
* vstack for vertical stacking
* c_ for column-wise stacking
* r_ for row-wise stacking

In [47]:
# Create numpy arrays
x = np.arange(7)
y = np.square(x)
print("x : ", x)
print("y : ", y)

x :  [0 1 2 3 4 5 6]
y :  [ 0  1  4  9 16 25 36]


In [48]:
# hstack Horizontal stacking
np.hstack([x,y])

array([ 0,  1,  2,  3,  4,  5,  6,  0,  1,  4,  9, 16, 25, 36])

In [49]:
# vstack Vertical stacking
np.vstack([x,y])

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  1,  4,  9, 16, 25, 36]])

In [50]:
# c_ Column-wise stacking
np.c_[x,y]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [51]:
# r_ Row-wise stacking
np.r_[x,y]

array([ 0,  1,  2,  3,  4,  5,  6,  0,  1,  4,  9, 16, 25, 36])

# **Duplicate numpy arrays**
* Use repeat and tile methods
* repeat for duplicating elements in numpy array
* tile for a layout that creates a matrix of required shape

In [52]:
# use repeat to duplicate numpy array values
print("x : ", x)
print("duplicate x values two times : ", np.repeat(x,2))

x :  [0 1 2 3 4 5 6]
duplicate x values two times :  [0 0 1 1 2 2 3 3 4 4 5 5 6 6]


In [53]:
# use tile to duplicate numpy array in a matrix format
print("x : ", x)
print("create a duplication of x two times in two rows of matrix : \n", np.tile(x,(2,1)))

x :  [0 1 2 3 4 5 6]
create a duplication of x two times in two rows of matrix : 
 [[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


# **Reshape numpy arrays using reshape method**

In [54]:
x = np.arange(8)
print("x : ", x)
print("Reshape x array into 2x4 matrix  : \n", np.reshape(x,(2,4)))
print("Reshape x array into 4x2 matrix : \n", x.reshape(4,2))

x :  [0 1 2 3 4 5 6 7]
Reshape x array into 2x4 matrix  : 
 [[0 1 2 3]
 [4 5 6 7]]
Reshape x array into 4x2 matrix : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [55]:
# reshape numpy arrays using Transpose using .T or .transpose()
print("x : ", x.reshape(2,4))
print("x.reshape(2,4) shape : ", x.reshape(2,4).shape)
print("x.reshape(2,4) transpose using .T : ", x.reshape(2,4).T)
print("x.reshape(2,4).T shape : ", x.reshape(2,4).T.shape)
print("x.reshape(2,4) transpose using transpose() method : ", x.reshape(2,4).transpose())
print("x.reshape(2,4).transpose(). shape : ", x.reshape(2,4).transpose().shape)

x :  [[0 1 2 3]
 [4 5 6 7]]
x.reshape(2,4) shape :  (2, 4)
x.reshape(2,4) transpose using .T :  [[0 4]
 [1 5]
 [2 6]
 [3 7]]
x.reshape(2,4).T shape :  (4, 2)
x.reshape(2,4) transpose using transpose() method :  [[0 4]
 [1 5]
 [2 6]
 [3 7]]
x.reshape(2,4).transpose(). shape :  (4, 2)


# **Logical operations**

In [56]:
print("x : ", x)
print("values in x greater than 3 : ", x>3)
print("values in x greater than 3 : ",np.where(x>3))

x :  [0 1 2 3 4 5 6 7]
values in x greater than 3 :  [False False False False  True  True  True  True]
values in x greater than 3 :  (array([4, 5, 6, 7]),)
